apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prostovid
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: prostovid
    newName: rg.fr-par.scw.cloud/djnd/prostovid
    newTag: '71a48febbd3da781444b63c93c797c5db594f046'
