name: Build and publish Docker image
on:
  push:
    branches:
      - "master"
jobs:
  push_to_registry:
    name: Build and push Docker image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Scaleway
        uses: docker/login-action@v3
        with:
          registry: rg.fr-par.scw.cloud/djnd
          username: nologin
          password: ${{ secrets.SCW_SECRET_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: .
          push: true
          tags: |
            rg.fr-par.scw.cloud/djnd/prostovid:${{ github.sha }}
            rg.fr-par.scw.cloud/djnd/prostovid:latest

      - name: Update image versions in kustomize/kustomization.yaml
        run: |
          sed -i "s/newTag: .*\+/newTag\: '${{ github.sha }}'/" kustomize/kustomization.yaml

      - name: Commit and push new image versions
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          message: "Update image versions in kustomize/kustomization.yaml"
